FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm ci && \
    npm run build --workspace client && \
    npm run build --workspace server

ENV NODE_ENV=production

EXPOSE 4000

CMD ["npm", "run", "start", "--workspace", "server"]
